version: "3"
services:
  db:
    image: mysql
    volumes: 
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  server:
    build: .
    volumes: 
      - ./src:/var/www/html
    links: 
      - db

  balancer:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./static:/data/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf