version: "3"
services:
  db:
    image: mysql
    volumes: 
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  server:
    build: .
    ports:
      - 8080:80
    volumes: 
      - ./src:/var/www/html
    depends_on:
      db:
        condition: service_healthy