version: "3.9"
services:
  db:
    image: mysql
    volumes: 
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: appDB
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  server:
    build: .
    ports:
      - 8080:80
    volumes: 
      - ./src:/var/www/html
    depends_on:
      db:
        condition: service_healthy