version: "3"
services:
  db:
    image: mysql
    volumes: 
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  server:
    build: .
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=appDB
      - DB_USER=root
      - DB_PASSWORD=password
    volumes: 
      - ./apache/src:/var/www/html
      - ./apache/conf/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    links: 
      - db

  balancer:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./static:/data/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  redis:
    image: redis
    ports:
      - 6379:6379